package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"strings"
)

type fieldSpec struct {
	GoName   string
	JSONName string
	Kind     string
	Rules    []string
}

func main() {
	var (
		inFile   = flag.String("in", "", "input Go file path")
		outFile  = flag.String("out", "", "output generated file path")
		typeName = flag.String("type", "", "target struct type name")
	)
	flag.Parse()

	if *inFile == "" || *outFile == "" || *typeName == "" {
		fail("usage: fields-validator-gen -in <file.go> -out <file.gen.go> -type <StructName>")
	}

	pkgName, fields := parseAnnotatedStruct(*inFile, *typeName)
	code := generateCode(pkgName, *typeName, fields)
	if err := os.WriteFile(*outFile, []byte(code), 0o644); err != nil {
		fail("write output: %v", err)
	}
}

func parseAnnotatedStruct(path, typeName string) (string, []fieldSpec) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
	if err != nil {
		fail("parse input file: %v", err)
	}

	var fields []fieldSpec
	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}
		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok || typeSpec.Name.Name != typeName {
				continue
			}
			st, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				fail("type %q is not a struct", typeName)
			}
			for _, f := range st.Fields.List {
				if len(f.Names) == 0 {
					continue
				}
				goName := f.Names[0].Name
				kind := exprKind(f.Type)
				if kind != "string" && kind != "int" && kind != "float64" &&
					kind != "*string" && kind != "*int" && kind != "*float64" {
					continue
				}

				rules := extractRulesFromComments(f.Doc, f.Comment)
				if len(rules) == 0 {
					continue
				}

				fields = append(fields, fieldSpec{
					GoName:   goName,
					JSONName: parseJSONTagName(f.Tag, goName),
					Kind:     kind,
					Rules:    rules,
				})
			}
		}
	}

	if len(fields) == 0 {
		fail("no annotated fields found for type %q", typeName)
	}

	return file.Name.Name, fields
}

func exprKind(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		inner := exprKind(t.X)
		if inner == "" {
			return ""
		}
		return "*" + inner
	default:
		return ""
	}
}

func extractRulesFromComments(doc, line *ast.CommentGroup) []string {
	var comments []string
	if doc != nil {
		for _, c := range doc.List {
			comments = append(comments, strings.TrimPrefix(c.Text, "//"))
		}
	}
	if line != nil {
		for _, c := range line.List {
			comments = append(comments, strings.TrimPrefix(c.Text, "//"))
		}
	}

	for _, raw := range comments {
		c := strings.TrimSpace(raw)
		if !strings.Contains(c, "@validate") {
			continue
		}
		idx := strings.Index(c, "@validate")
		s := strings.TrimSpace(c[idx+len("@validate"):])
		if s == "" {
			return nil
		}
		parts := strings.Split(s, ",")
		out := make([]string, 0, len(parts))
		for _, p := range parts {
			r := strings.TrimSpace(p)
			if r != "" {
				out = append(out, r)
			}
		}
		return out
	}
	return nil
}

func parseJSONTagName(tag *ast.BasicLit, fallback string) string {
	defaultName := fallback
	if len(defaultName) > 0 {
		defaultName = strings.ToLower(defaultName[:1]) + defaultName[1:]
	}
	if tag == nil {
		return defaultName
	}
	trimmed := strings.Trim(tag.Value, "`")
	parts := strings.Split(trimmed, " ")
	for _, p := range parts {
		if !strings.HasPrefix(p, "json:\"") {
			continue
		}
		value := strings.TrimPrefix(p, "json:\"")
		value = strings.TrimSuffix(value, "\"")
		name := strings.Split(value, ",")[0]
		if name == "" || name == "-" {
			return defaultName
		}
		return name
	}
	return defaultName
}

func generateCode(pkgName, typeName string, fields []fieldSpec) string {
	var b bytes.Buffer
	b.WriteString("// Code generated by fields-validator-gen. DO NOT EDIT.\n")
	b.WriteString("package " + pkgName + "\n\n")
	b.WriteString("import \"fields-validator/validate\"\n\n")

	b.WriteString("func (in " + typeName + ") ValidateCollect() validate.Errors {\n")
	b.WriteString("\tvar errs validate.Errors\n\n")

	for _, f := range fields {
		switch f.Kind {
		case "string":
			b.WriteString("\terrs = append(errs, validate.ApplyStringRules(\n")
			b.WriteString("\t\t\"" + f.JSONName + "\",\n")
			b.WriteString("\t\tin." + f.GoName + ",\n")
			for _, r := range f.Rules {
				b.WriteString("\t\t" + mapStringRule(r) + ",\n")
			}
			b.WriteString("\t)...)\n\n")
		case "*string":
			b.WriteString("\terrs = append(errs, validate.ApplyStringPtrRules(\n")
			b.WriteString("\t\t\"" + f.JSONName + "\",\n")
			b.WriteString("\t\tin." + f.GoName + ",\n")
			for _, r := range f.Rules {
				b.WriteString("\t\t" + mapStringPtrRule(r) + ",\n")
			}
			b.WriteString("\t)...)\n\n")
		case "int":
			b.WriteString("\terrs = append(errs, validate.ApplyIntRules(\n")
			b.WriteString("\t\t\"" + f.JSONName + "\",\n")
			b.WriteString("\t\tin." + f.GoName + ",\n")
			for _, r := range f.Rules {
				b.WriteString("\t\t" + mapIntRule(r) + ",\n")
			}
			b.WriteString("\t)...)\n\n")
		case "*int":
			b.WriteString("\terrs = append(errs, validate.ApplyIntPtrRules(\n")
			b.WriteString("\t\t\"" + f.JSONName + "\",\n")
			b.WriteString("\t\tin." + f.GoName + ",\n")
			for _, r := range f.Rules {
				b.WriteString("\t\t" + mapIntPtrRule(r) + ",\n")
			}
			b.WriteString("\t)...)\n\n")
		case "float64":
			b.WriteString("\terrs = append(errs, validate.ApplyFloatRules(\n")
			b.WriteString("\t\t\"" + f.JSONName + "\",\n")
			b.WriteString("\t\tin." + f.GoName + ",\n")
			for _, r := range f.Rules {
				b.WriteString("\t\t" + mapFloatRule(r) + ",\n")
			}
			b.WriteString("\t)...)\n\n")
		case "*float64":
			b.WriteString("\terrs = append(errs, validate.ApplyFloatPtrRules(\n")
			b.WriteString("\t\t\"" + f.JSONName + "\",\n")
			b.WriteString("\t\tin." + f.GoName + ",\n")
			for _, r := range f.Rules {
				b.WriteString("\t\t" + mapFloatPtrRule(r) + ",\n")
			}
			b.WriteString("\t)...)\n\n")
		}
	}

	b.WriteString("\treturn errs\n")
	b.WriteString("}\n")
	return b.String()
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "fields-validator-gen: "+format+"\n", args...)
	os.Exit(1)
}
