// Code generated by fields-validator-gen. DO NOT EDIT.
package main

import "fields-validator/validate"

func (in InputDTO) ValidateCollect() validate.Errors {
	var errs validate.Errors

	errs = append(errs, validate.ApplyStringRules(
		"name",
		in.Name,
		validate.Required(),
		validate.Contains("Isaac"),
	)...)

	errs = append(errs, validate.ApplyIntRules(
		"age",
		in.Age,
		validate.Min(18),
		validate.Max(120),
		validate.EqualsInt(18),
		validate.ContainsInt(1),
	)...)

	errs = append(errs, validate.ApplyStringRules(
		"email",
		in.Email,
		validate.Required(),
		validate.Email(),
	)...)

	errs = append(errs, validate.ApplyFloatRules(
		"amount",
		in.Amount,
		validate.EqualsFloat(1.8),
		validate.ContainsFloat(1.8),
	)...)

	errs = append(errs, validate.ApplyStringRules(
		"status",
		in.Status,
		validate.OneOf("PAGAMENTO", "PAGADO", "QUITADO"),
	)...)

	errs = append(errs, validate.ApplyStringPtrRules(
		"username",
		in.Username,
		validate.PtrNotNil(),
		validate.PtrString(validate.Required()),
		validate.PtrString(validate.MinLen(3)),
		validate.PtrString(validate.MaxLen(20)),
	)...)

	errs = append(errs, validate.ApplyStringRules(
		"date",
		in.Date,
		validate.Date("YYYY-MM-DD"),
	)...)

	errs = append(errs, validate.ApplyStringRules(
		"time",
		in.Time,
		validate.Time("HH:MM:SS"),
	)...)

	errs = append(errs, validate.ApplyStringRules(
		"dateTime",
		in.DateTime,
		validate.DateTime("YYYY-MM-DD HH:MM:SS"),
	)...)

	return errs
}
